
services:
  db:
    image: postgres:15
    container_name: f1_telemetry_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: f1_telemetry_fast_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://f1user:f1password@f1_telemetry_db:5432/f1_telemetry
    ports:
      - "8000:8000"

volumes:
  pg_data: