"""added models and relationships

Revision ID: 7eaf556f22d3
Revises: e9b24973ee4b
Create Date: 2025-03-11 00:24:24.083895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eaf556f22d3'
down_revision: Union[str, None] = 'e9b24973ee4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('circuits', 'circuitRef',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('circuits', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('drivers', 'driverRef',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('drivers', 'forename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('drivers', 'surname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drivers', 'surname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('drivers', 'forename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('drivers', 'driverRef',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('circuits', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('circuits', 'circuitRef',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
